//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCSharp.ws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ws.BancoWS")]
    public interface BancoWS {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarNumerosContasClienteRequest", ReplyAction="http://ws/BancoWS/consultarNumerosContasClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.consultarNumerosContasClienteResponse consultarNumerosContasCliente(ClienteCSharp.ws.consultarNumerosContasClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarNumerosContasClienteRequest", ReplyAction="http://ws/BancoWS/consultarNumerosContasClienteResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarNumerosContasClienteResponse> consultarNumerosContasClienteAsync(ClienteCSharp.ws.consultarNumerosContasClienteRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarCadastroRequest", ReplyAction="http://ws/BancoWS/consultarCadastroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.consultarCadastroResponse consultarCadastro(ClienteCSharp.ws.consultarCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarCadastroRequest", ReplyAction="http://ws/BancoWS/consultarCadastroResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarCadastroResponse> consultarCadastroAsync(ClienteCSharp.ws.consultarCadastroRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarTransferenciaRequest", ReplyAction="http://ws/BancoWS/realizarTransferenciaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.realizarTransferenciaResponse realizarTransferencia(ClienteCSharp.ws.realizarTransferenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarTransferenciaRequest", ReplyAction="http://ws/BancoWS/realizarTransferenciaResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarTransferenciaResponse> realizarTransferenciaAsync(ClienteCSharp.ws.realizarTransferenciaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarDepositoRequest", ReplyAction="http://ws/BancoWS/realizarDepositoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.realizarDepositoResponse realizarDeposito(ClienteCSharp.ws.realizarDepositoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarDepositoRequest", ReplyAction="http://ws/BancoWS/realizarDepositoResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarDepositoResponse> realizarDepositoAsync(ClienteCSharp.ws.realizarDepositoRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarExtratoRequest", ReplyAction="http://ws/BancoWS/consultarExtratoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.consultarExtratoResponse consultarExtrato(ClienteCSharp.ws.consultarExtratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarExtratoRequest", ReplyAction="http://ws/BancoWS/consultarExtratoResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarExtratoResponse> consultarExtratoAsync(ClienteCSharp.ws.consultarExtratoRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarSaqueRequest", ReplyAction="http://ws/BancoWS/realizarSaqueResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.realizarSaqueResponse realizarSaque(ClienteCSharp.ws.realizarSaqueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/realizarSaqueRequest", ReplyAction="http://ws/BancoWS/realizarSaqueResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarSaqueResponse> realizarSaqueAsync(ClienteCSharp.ws.realizarSaqueRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarSaldoRequest", ReplyAction="http://ws/BancoWS/consultarSaldoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.consultarSaldoResponse consultarSaldo(ClienteCSharp.ws.consultarSaldoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/consultarSaldoRequest", ReplyAction="http://ws/BancoWS/consultarSaldoResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarSaldoResponse> consultarSaldoAsync(ClienteCSharp.ws.consultarSaldoRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/criarCadastroRequest", ReplyAction="http://ws/BancoWS/criarCadastroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.criarCadastroResponse criarCadastro(ClienteCSharp.ws.criarCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/criarCadastroRequest", ReplyAction="http://ws/BancoWS/criarCadastroResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.criarCadastroResponse> criarCadastroAsync(ClienteCSharp.ws.criarCadastroRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/criarContaRequest", ReplyAction="http://ws/BancoWS/criarContaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.criarContaResponse criarConta(ClienteCSharp.ws.criarContaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/criarContaRequest", ReplyAction="http://ws/BancoWS/criarContaResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.criarContaResponse> criarContaAsync(ClienteCSharp.ws.criarContaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/alterarCadastroRequest", ReplyAction="http://ws/BancoWS/alterarCadastroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteCSharp.ws.alterarCadastroResponse alterarCadastro(ClienteCSharp.ws.alterarCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/BancoWS/alterarCadastroRequest", ReplyAction="http://ws/BancoWS/alterarCadastroResponse")]
        System.Threading.Tasks.Task<ClienteCSharp.ws.alterarCadastroResponse> alterarCadastroAsync(ClienteCSharp.ws.alterarCadastroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNumerosContasCliente", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarNumerosContasClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF;
        
        public consultarNumerosContasClienteRequest() {
        }
        
        public consultarNumerosContasClienteRequest(string CPF) {
            this.CPF = CPF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNumerosContasClienteResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarNumerosContasClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int[] @return;
        
        public consultarNumerosContasClienteResponse() {
        }
        
        public consultarNumerosContasClienteResponse(int[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class cliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cPFField;
        
        private string nomeField;

        public cliente(string cPF, string nome)
        {
            CPF = cPF;
            this.nome = nome;
        }

        public cliente()
        {
            CPF = "";
            this.nome = "";
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
                this.RaisePropertyChanged("CPF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCadastro", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF;
        
        public consultarCadastroRequest() {
        }
        
        public consultarCadastroRequest(string CPF) {
            this.CPF = CPF;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarCadastroResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCSharp.ws.cliente @return;
        
        public consultarCadastroResponse() {
        }
        
        public consultarCadastroResponse(ClienteCSharp.ws.cliente @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarTransferencia", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarTransferenciaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int contaOrigem;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int contaDestino;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valor;
        
        public realizarTransferenciaRequest() {
        }
        
        public realizarTransferenciaRequest(int contaOrigem, int contaDestino, double valor) {
            this.contaOrigem = contaOrigem;
            this.contaDestino = contaDestino;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarTransferenciaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarTransferenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public realizarTransferenciaResponse() {
        }
        
        public realizarTransferenciaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarDeposito", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarDepositoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int conta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valor;
        
        public realizarDepositoRequest() {
        }
        
        public realizarDepositoRequest(int conta, double valor) {
            this.conta = conta;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarDepositoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarDepositoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public realizarDepositoResponse() {
        }
        
        public realizarDepositoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarExtrato", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarExtratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int conta;
        
        public consultarExtratoRequest() {
        }
        
        public consultarExtratoRequest(int conta) {
            this.conta = conta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarExtratoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarExtratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public consultarExtratoResponse() {
        }
        
        public consultarExtratoResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarSaque", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarSaqueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int conta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valor;
        
        public realizarSaqueRequest() {
        }
        
        public realizarSaqueRequest(int conta, double valor) {
            this.conta = conta;
            this.valor = valor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="realizarSaqueResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class realizarSaqueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public realizarSaqueResponse() {
        }
        
        public realizarSaqueResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldo", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarSaldoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int conta;
        
        public consultarSaldoRequest() {
        }
        
        public consultarSaldoRequest(int conta) {
            this.conta = conta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSaldoResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class consultarSaldoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public consultarSaldoResponse() {
        }
        
        public consultarSaldoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="criarCadastro", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class criarCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCSharp.ws.cliente cliente;
        
        public criarCadastroRequest() {
        }
        
        public criarCadastroRequest(ClienteCSharp.ws.cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="criarCadastroResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class criarCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public criarCadastroResponse() {
        }
        
        public criarCadastroResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="criarConta", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class criarContaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CPF;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double saldo;
        
        public criarContaRequest() {
        }
        
        public criarContaRequest(string CPF, double saldo) {
            this.CPF = CPF;
            this.saldo = saldo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="criarContaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class criarContaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public criarContaResponse() {
        }
        
        public criarContaResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alterarCadastro", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class alterarCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ClienteCSharp.ws.cliente cliente;
        
        public alterarCadastroRequest() {
        }
        
        public alterarCadastroRequest(ClienteCSharp.ws.cliente cliente) {
            this.cliente = cliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="alterarCadastroResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class alterarCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public alterarCadastroResponse() {
        }
        
        public alterarCadastroResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BancoWSChannel : ClienteCSharp.ws.BancoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BancoWSClient : System.ServiceModel.ClientBase<ClienteCSharp.ws.BancoWS>, ClienteCSharp.ws.BancoWS {
        
        public BancoWSClient() {
        }
        
        public BancoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BancoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BancoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.consultarNumerosContasClienteResponse ClienteCSharp.ws.BancoWS.consultarNumerosContasCliente(ClienteCSharp.ws.consultarNumerosContasClienteRequest request) {
            return base.Channel.consultarNumerosContasCliente(request);
        }
        
        public int[] consultarNumerosContasCliente(string CPF) {
            ClienteCSharp.ws.consultarNumerosContasClienteRequest inValue = new ClienteCSharp.ws.consultarNumerosContasClienteRequest();
            inValue.CPF = CPF;
            ClienteCSharp.ws.consultarNumerosContasClienteResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).consultarNumerosContasCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarNumerosContasClienteResponse> ClienteCSharp.ws.BancoWS.consultarNumerosContasClienteAsync(ClienteCSharp.ws.consultarNumerosContasClienteRequest request) {
            return base.Channel.consultarNumerosContasClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.consultarNumerosContasClienteResponse> consultarNumerosContasClienteAsync(string CPF) {
            ClienteCSharp.ws.consultarNumerosContasClienteRequest inValue = new ClienteCSharp.ws.consultarNumerosContasClienteRequest();
            inValue.CPF = CPF;
            return ((ClienteCSharp.ws.BancoWS)(this)).consultarNumerosContasClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.consultarCadastroResponse ClienteCSharp.ws.BancoWS.consultarCadastro(ClienteCSharp.ws.consultarCadastroRequest request) {
            return base.Channel.consultarCadastro(request);
        }
        
        public ClienteCSharp.ws.cliente consultarCadastro(string CPF) {
            ClienteCSharp.ws.consultarCadastroRequest inValue = new ClienteCSharp.ws.consultarCadastroRequest();
            inValue.CPF = CPF;
            ClienteCSharp.ws.consultarCadastroResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).consultarCadastro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarCadastroResponse> ClienteCSharp.ws.BancoWS.consultarCadastroAsync(ClienteCSharp.ws.consultarCadastroRequest request) {
            return base.Channel.consultarCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.consultarCadastroResponse> consultarCadastroAsync(string CPF) {
            ClienteCSharp.ws.consultarCadastroRequest inValue = new ClienteCSharp.ws.consultarCadastroRequest();
            inValue.CPF = CPF;
            return ((ClienteCSharp.ws.BancoWS)(this)).consultarCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.realizarTransferenciaResponse ClienteCSharp.ws.BancoWS.realizarTransferencia(ClienteCSharp.ws.realizarTransferenciaRequest request) {
            return base.Channel.realizarTransferencia(request);
        }
        
        public bool realizarTransferencia(int contaOrigem, int contaDestino, double valor) {
            ClienteCSharp.ws.realizarTransferenciaRequest inValue = new ClienteCSharp.ws.realizarTransferenciaRequest();
            inValue.contaOrigem = contaOrigem;
            inValue.contaDestino = contaDestino;
            inValue.valor = valor;
            ClienteCSharp.ws.realizarTransferenciaResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).realizarTransferencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarTransferenciaResponse> ClienteCSharp.ws.BancoWS.realizarTransferenciaAsync(ClienteCSharp.ws.realizarTransferenciaRequest request) {
            return base.Channel.realizarTransferenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.realizarTransferenciaResponse> realizarTransferenciaAsync(int contaOrigem, int contaDestino, double valor) {
            ClienteCSharp.ws.realizarTransferenciaRequest inValue = new ClienteCSharp.ws.realizarTransferenciaRequest();
            inValue.contaOrigem = contaOrigem;
            inValue.contaDestino = contaDestino;
            inValue.valor = valor;
            return ((ClienteCSharp.ws.BancoWS)(this)).realizarTransferenciaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.realizarDepositoResponse ClienteCSharp.ws.BancoWS.realizarDeposito(ClienteCSharp.ws.realizarDepositoRequest request) {
            return base.Channel.realizarDeposito(request);
        }
        
        public bool realizarDeposito(int conta, double valor) {
            ClienteCSharp.ws.realizarDepositoRequest inValue = new ClienteCSharp.ws.realizarDepositoRequest();
            inValue.conta = conta;
            inValue.valor = valor;
            ClienteCSharp.ws.realizarDepositoResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).realizarDeposito(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarDepositoResponse> ClienteCSharp.ws.BancoWS.realizarDepositoAsync(ClienteCSharp.ws.realizarDepositoRequest request) {
            return base.Channel.realizarDepositoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.realizarDepositoResponse> realizarDepositoAsync(int conta, double valor) {
            ClienteCSharp.ws.realizarDepositoRequest inValue = new ClienteCSharp.ws.realizarDepositoRequest();
            inValue.conta = conta;
            inValue.valor = valor;
            return ((ClienteCSharp.ws.BancoWS)(this)).realizarDepositoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.consultarExtratoResponse ClienteCSharp.ws.BancoWS.consultarExtrato(ClienteCSharp.ws.consultarExtratoRequest request) {
            return base.Channel.consultarExtrato(request);
        }
        
        public string[] consultarExtrato(int conta) {
            ClienteCSharp.ws.consultarExtratoRequest inValue = new ClienteCSharp.ws.consultarExtratoRequest();
            inValue.conta = conta;
            ClienteCSharp.ws.consultarExtratoResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).consultarExtrato(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarExtratoResponse> ClienteCSharp.ws.BancoWS.consultarExtratoAsync(ClienteCSharp.ws.consultarExtratoRequest request) {
            return base.Channel.consultarExtratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.consultarExtratoResponse> consultarExtratoAsync(int conta) {
            ClienteCSharp.ws.consultarExtratoRequest inValue = new ClienteCSharp.ws.consultarExtratoRequest();
            inValue.conta = conta;
            return ((ClienteCSharp.ws.BancoWS)(this)).consultarExtratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.realizarSaqueResponse ClienteCSharp.ws.BancoWS.realizarSaque(ClienteCSharp.ws.realizarSaqueRequest request) {
            return base.Channel.realizarSaque(request);
        }
        
        public bool realizarSaque(int conta, double valor) {
            ClienteCSharp.ws.realizarSaqueRequest inValue = new ClienteCSharp.ws.realizarSaqueRequest();
            inValue.conta = conta;
            inValue.valor = valor;
            ClienteCSharp.ws.realizarSaqueResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).realizarSaque(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.realizarSaqueResponse> ClienteCSharp.ws.BancoWS.realizarSaqueAsync(ClienteCSharp.ws.realizarSaqueRequest request) {
            return base.Channel.realizarSaqueAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.realizarSaqueResponse> realizarSaqueAsync(int conta, double valor) {
            ClienteCSharp.ws.realizarSaqueRequest inValue = new ClienteCSharp.ws.realizarSaqueRequest();
            inValue.conta = conta;
            inValue.valor = valor;
            return ((ClienteCSharp.ws.BancoWS)(this)).realizarSaqueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.consultarSaldoResponse ClienteCSharp.ws.BancoWS.consultarSaldo(ClienteCSharp.ws.consultarSaldoRequest request) {
            return base.Channel.consultarSaldo(request);
        }
        
        public double consultarSaldo(int conta) {
            ClienteCSharp.ws.consultarSaldoRequest inValue = new ClienteCSharp.ws.consultarSaldoRequest();
            inValue.conta = conta;
            ClienteCSharp.ws.consultarSaldoResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).consultarSaldo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.consultarSaldoResponse> ClienteCSharp.ws.BancoWS.consultarSaldoAsync(ClienteCSharp.ws.consultarSaldoRequest request) {
            return base.Channel.consultarSaldoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.consultarSaldoResponse> consultarSaldoAsync(int conta) {
            ClienteCSharp.ws.consultarSaldoRequest inValue = new ClienteCSharp.ws.consultarSaldoRequest();
            inValue.conta = conta;
            return ((ClienteCSharp.ws.BancoWS)(this)).consultarSaldoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.criarCadastroResponse ClienteCSharp.ws.BancoWS.criarCadastro(ClienteCSharp.ws.criarCadastroRequest request) {
            return base.Channel.criarCadastro(request);
        }
        
        public bool criarCadastro(ClienteCSharp.ws.cliente cliente) {
            ClienteCSharp.ws.criarCadastroRequest inValue = new ClienteCSharp.ws.criarCadastroRequest();
            inValue.cliente = cliente;
            ClienteCSharp.ws.criarCadastroResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).criarCadastro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.criarCadastroResponse> ClienteCSharp.ws.BancoWS.criarCadastroAsync(ClienteCSharp.ws.criarCadastroRequest request) {
            return base.Channel.criarCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.criarCadastroResponse> criarCadastroAsync(ClienteCSharp.ws.cliente cliente) {
            ClienteCSharp.ws.criarCadastroRequest inValue = new ClienteCSharp.ws.criarCadastroRequest();
            inValue.cliente = cliente;
            return ((ClienteCSharp.ws.BancoWS)(this)).criarCadastroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.criarContaResponse ClienteCSharp.ws.BancoWS.criarConta(ClienteCSharp.ws.criarContaRequest request) {
            return base.Channel.criarConta(request);
        }
        
        public bool criarConta(string CPF, double saldo) {
            ClienteCSharp.ws.criarContaRequest inValue = new ClienteCSharp.ws.criarContaRequest();
            inValue.CPF = CPF;
            inValue.saldo = saldo;
            ClienteCSharp.ws.criarContaResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).criarConta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.criarContaResponse> ClienteCSharp.ws.BancoWS.criarContaAsync(ClienteCSharp.ws.criarContaRequest request) {
            return base.Channel.criarContaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.criarContaResponse> criarContaAsync(string CPF, double saldo) {
            ClienteCSharp.ws.criarContaRequest inValue = new ClienteCSharp.ws.criarContaRequest();
            inValue.CPF = CPF;
            inValue.saldo = saldo;
            return ((ClienteCSharp.ws.BancoWS)(this)).criarContaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteCSharp.ws.alterarCadastroResponse ClienteCSharp.ws.BancoWS.alterarCadastro(ClienteCSharp.ws.alterarCadastroRequest request) {
            return base.Channel.alterarCadastro(request);
        }
        
        public bool alterarCadastro(ClienteCSharp.ws.cliente cliente) {
            ClienteCSharp.ws.alterarCadastroRequest inValue = new ClienteCSharp.ws.alterarCadastroRequest();
            inValue.cliente = cliente;
            ClienteCSharp.ws.alterarCadastroResponse retVal = ((ClienteCSharp.ws.BancoWS)(this)).alterarCadastro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteCSharp.ws.alterarCadastroResponse> ClienteCSharp.ws.BancoWS.alterarCadastroAsync(ClienteCSharp.ws.alterarCadastroRequest request) {
            return base.Channel.alterarCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteCSharp.ws.alterarCadastroResponse> alterarCadastroAsync(ClienteCSharp.ws.cliente cliente) {
            ClienteCSharp.ws.alterarCadastroRequest inValue = new ClienteCSharp.ws.alterarCadastroRequest();
            inValue.cliente = cliente;
            return ((ClienteCSharp.ws.BancoWS)(this)).alterarCadastroAsync(inValue);
        }
    }
}
