//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ws {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="ws.WSAndroid")]
    public interface WSAndroid {
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/helloRequest", ReplyAction="http://ws/WSAndroid/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.ws.helloResponse hello(Cliente.ws.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/helloRequest", ReplyAction="http://ws/WSAndroid/helloResponse")]
        System.Threading.Tasks.Task<Cliente.ws.helloResponse> helloAsync(Cliente.ws.helloRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/somaRequest", ReplyAction="http://ws/WSAndroid/somaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.ws.somaResponse soma(Cliente.ws.somaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/somaRequest", ReplyAction="http://ws/WSAndroid/somaResponse")]
        System.Threading.Tasks.Task<Cliente.ws.somaResponse> somaAsync(Cliente.ws.somaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaListaRequest", ReplyAction="http://ws/WSAndroid/retornaListaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.ws.retornaListaResponse retornaLista(Cliente.ws.retornaListaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaListaRequest", ReplyAction="http://ws/WSAndroid/retornaListaResponse")]
        System.Threading.Tasks.Task<Cliente.ws.retornaListaResponse> retornaListaAsync(Cliente.ws.retornaListaRequest request);
        
        // CODEGEN: O parâmetro 'return' requer informações adicionais de esquema que não podem ser capturadas usando o modo do parâmetro. O atributo específico é 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaLivroRequest", ReplyAction="http://ws/WSAndroid/retornaLivroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Cliente.ws.retornaLivroResponse retornaLivro(Cliente.ws.retornaLivroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSAndroid/retornaLivroRequest", ReplyAction="http://ws/WSAndroid/retornaLivroResponse")]
        System.Threading.Tasks.Task<Cliente.ws.retornaLivroResponse> retornaLivroAsync(Cliente.ws.retornaLivroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="soma", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class somaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double num1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double num2;
        
        public somaRequest() {
        }
        
        public somaRequest(double num1, double num2) {
            this.num1 = num1;
            this.num2 = num2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="somaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class somaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public somaResponse() {
        }
        
        public somaResponse(double @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws/")]
    public partial class livro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int anoField;
        
        private string editoraField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int ano {
            get {
                return this.anoField;
            }
            set {
                this.anoField = value;
                this.RaisePropertyChanged("ano");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string editora {
            get {
                return this.editoraField;
            }
            set {
                this.editoraField = value;
                this.RaisePropertyChanged("editora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLista", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaListaRequest {
        
        public retornaListaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaListaResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaListaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.ws.livro[] @return;
        
        public retornaListaResponse() {
        }
        
        public retornaListaResponse(Cliente.ws.livro[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLivro", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaLivroRequest {
        
        public retornaLivroRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="retornaLivroResponse", WrapperNamespace="http://ws/", IsWrapped=true)]
    public partial class retornaLivroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Cliente.ws.livro @return;
        
        public retornaLivroResponse() {
        }
        
        public retornaLivroResponse(Cliente.ws.livro @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAndroidChannel : Cliente.ws.WSAndroid, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAndroidClient : System.ServiceModel.ClientBase<Cliente.ws.WSAndroid>, Cliente.ws.WSAndroid {
        
        public WSAndroidClient() {
        }
        
        public WSAndroidClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAndroidClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAndroidClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAndroidClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ws.helloResponse Cliente.ws.WSAndroid.hello(Cliente.ws.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            Cliente.ws.helloRequest inValue = new Cliente.ws.helloRequest();
            inValue.name = name;
            Cliente.ws.helloResponse retVal = ((Cliente.ws.WSAndroid)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ws.helloResponse> Cliente.ws.WSAndroid.helloAsync(Cliente.ws.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ws.helloResponse> helloAsync(string name) {
            Cliente.ws.helloRequest inValue = new Cliente.ws.helloRequest();
            inValue.name = name;
            return ((Cliente.ws.WSAndroid)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ws.somaResponse Cliente.ws.WSAndroid.soma(Cliente.ws.somaRequest request) {
            return base.Channel.soma(request);
        }
        
        public double soma(double num1, double num2) {
            Cliente.ws.somaRequest inValue = new Cliente.ws.somaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            Cliente.ws.somaResponse retVal = ((Cliente.ws.WSAndroid)(this)).soma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ws.somaResponse> Cliente.ws.WSAndroid.somaAsync(Cliente.ws.somaRequest request) {
            return base.Channel.somaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ws.somaResponse> somaAsync(double num1, double num2) {
            Cliente.ws.somaRequest inValue = new Cliente.ws.somaRequest();
            inValue.num1 = num1;
            inValue.num2 = num2;
            return ((Cliente.ws.WSAndroid)(this)).somaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ws.retornaListaResponse Cliente.ws.WSAndroid.retornaLista(Cliente.ws.retornaListaRequest request) {
            return base.Channel.retornaLista(request);
        }
        
        public Cliente.ws.livro[] retornaLista() {
            Cliente.ws.retornaListaRequest inValue = new Cliente.ws.retornaListaRequest();
            Cliente.ws.retornaListaResponse retVal = ((Cliente.ws.WSAndroid)(this)).retornaLista(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ws.retornaListaResponse> Cliente.ws.WSAndroid.retornaListaAsync(Cliente.ws.retornaListaRequest request) {
            return base.Channel.retornaListaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ws.retornaListaResponse> retornaListaAsync() {
            Cliente.ws.retornaListaRequest inValue = new Cliente.ws.retornaListaRequest();
            return ((Cliente.ws.WSAndroid)(this)).retornaListaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.ws.retornaLivroResponse Cliente.ws.WSAndroid.retornaLivro(Cliente.ws.retornaLivroRequest request) {
            return base.Channel.retornaLivro(request);
        }
        
        public Cliente.ws.livro retornaLivro() {
            Cliente.ws.retornaLivroRequest inValue = new Cliente.ws.retornaLivroRequest();
            Cliente.ws.retornaLivroResponse retVal = ((Cliente.ws.WSAndroid)(this)).retornaLivro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.ws.retornaLivroResponse> Cliente.ws.WSAndroid.retornaLivroAsync(Cliente.ws.retornaLivroRequest request) {
            return base.Channel.retornaLivroAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.ws.retornaLivroResponse> retornaLivroAsync() {
            Cliente.ws.retornaLivroRequest inValue = new Cliente.ws.retornaLivroRequest();
            return ((Cliente.ws.WSAndroid)(this)).retornaLivroAsync(inValue);
        }
    }
}
